site_name: Differential Equations
site_url: https://ananasdda.github.io/DifferentialEquations/
repo_name: ananasDDA/DifferentialEquations
repo_url: https://github.com/ananasDDA/DifferentialEquations

theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Переключить на тёмную тему
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Главная: index.md
  - Курс:
    - Введение: content/introduction.md
    - Уравнения первого порядка: content/first-order.md
    - Уравнения второго порядка: content/second-order.md
    - Системы уравнений: content/systems.md
  - Материалы:
    - Лекции: resources/lecture-notes.md
    - Задачи: resources/practice.md
    - Дополнительно: resources/materials.md

extra_css:
  - stylesheets/extra.css